### ISSUE TITLE
Error when save a subscription (ADMIN)

### ISSUE THREAD

**Issue by CARocha** [thismatters/django-mailinglist#12]
Hello, i have an error when try to save the subscriber in admin
my stack is
Django>=4.2,<5.1
wagtail>=6.0,<6.1
psycopg2-binary==2.9.9
django-allauth==0.61.1
django-debug-toolbar==4.3.0
django-mailinglist==0.1.7

and this is the error:
ValueError at /django-admin/mailinglist/subscription/add/
empty range for randrange() (0, 0, 0)

Exception Location:	/Users/user/.pyenv/versions/3.11.4/lib/python3.11/random.py, line 345, in randrange

Any idea to solve this error?

**Comment by thismatters** [comment]
Hello,

Could you please post the full traceback? It may be necessary to copy it from the shell (rather than the browser).

Thanks
