### ISSUE TITLE
url problems

### ISSUE THREAD

**Issue by wilsonchen1** [thismatters/django-mailinglist#9]
hi! I used your mailinglist, but found that when using postman to request the mailinglist route in the local environment, it can take effect, but in the online environment, a 404 error will be reported. I checked the problem and found that the mailinglist code can be seen online, and I tried to use the code of service.py, and it was feasible online. So what could be the problem?

**Comment by wilsonchen1** [comment]
<img width="593" alt="image" src="https://github.com/thismatters/django-mailinglist/assets/105147548/0b606a26-1973-4564-b777-670f574a6812">
<img width="768" alt="image" src="https://github.com/thismatters/django-mailinglist/assets/105147548/dc6d60f8-874d-4523-8f23-b2dce57b0c8d">
<img width="843" alt="image" src="https://github.com/thismatters/django-mailinglist/assets/105147548/9be8e626-f2cf-4a14-9be1-9e52007e4136">

**Comment by thismatters** [comment]
Hello! Could you show me where and how you got the 404 error?

**Comment by thismatters** [comment]
Hello, are you still seeing this issue?

**Comment by thismatters** [comment]
If you are still seeing this 404 please reopen this issue.

**Comment by wilsonchen1** [comment]
thank you, im not seeing this issue.&nbsp; i was in new Year vacation so i forgot to reply to your email. sorry! hope we can connect in the future.




赫赫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thismatters/django-mailinglist"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月30日(星期六) 晚上8:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thismatters/django-mailinglist] url problems (Issue #9)





 
If you are still seeing this 404 please reopen this issue.
